//! Repository chores.
//!
//! `spec-lint` enforces the one rule that keeps the format honest: the
//! committed vector bytes may not change while the format version stays put.
//! Without it, an innocent-looking refactor can silently alter the wire format,
//! and a regenerated corpus will happily agree with the new behaviour — at
//! which point the corpus has stopped being evidence and become a mirror.
//!
//! `doctor` checks the build environment. It lives here rather than in the
//! user-facing CLI because it is a developer concern; shipping "why is my
//! toolchain wrong" as a subcommand of a security tool would be odd.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use anyhow::{bail, Context, Result};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("workspace root")
}

fn main() -> ExitCode {
    let task = std::env::args().nth(1).unwrap_or_default();
    let result = match task.as_str() {
        "spec-lint" => spec_lint(),
        "doctor" => doctor(),
        other => {
            eprintln!("unknown task {other:?}; expected `spec-lint` or `doctor`");
            return ExitCode::FAILURE;
        }
    };

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e:#}");
            ExitCode::FAILURE
        }
    }
}

fn spec_lint() -> Result<()> {
    let root = repo_root();
    let vectors = root.join("spec/vectors");
    let manifest_path = vectors.join("vectors.json");

    let raw = std::fs::read_to_string(&manifest_path)
        .with_context(|| format!("reading {}", manifest_path.display()))?;
    let manifest: serde_json::Value = serde_json::from_str(&raw)?;

    let declared = manifest["format_version"]
        .as_u64()
        .context("manifest is missing format_version")? as u8;

    if declared != sirna_core::FORMAT_VERSION {
        bail!(
            "the corpus targets format version {declared} but this build produces {}.\n\
             If the wire format changed on purpose, bump the version in spec/ENVELOPE.md \
             and regenerate. If it changed by accident, that is the bug.",
            sirna_core::FORMAT_VERSION
        );
    }

    // Every recorded hash must still match the file on disk. This catches a
    // .bin edited by hand, or regenerated by a build whose behaviour drifted,
    // without anyone noticing.
    let entries = manifest["vectors"]
        .as_array()
        .context("manifest is missing the vectors array")?;
    let mut checked = 0usize;

    for v in entries {
        let id = v["id"].as_str().context("vector without an id")?;
        let file = v["envelope_file"]
            .as_str()
            .with_context(|| format!("{id}: missing envelope_file"))?;
        let want = v["envelope_b3"]
            .as_str()
            .with_context(|| format!("{id}: missing envelope_b3"))?;

        let bytes =
            std::fs::read(vectors.join(file)).with_context(|| format!("{id}: reading {file}"))?;
        let got = blake3::hash(&bytes).to_hex().to_string();

        if got != want {
            bail!(
                "{id}: {file} does not match the hash recorded in the manifest.\n\
                 Regenerate the corpus, and if the bytes really did change, bump the \
                 format version — vectors are a contract, not a cache."
            );
        }
        checked += 1;
    }

    // The spec document declares the version too, and it is the normative
    // source. Three places disagreeing is how a format quietly forks.
    let spec = std::fs::read_to_string(root.join("spec/ENVELOPE.md"))?;
    let heading = format!(
        "# Sirna envelope format — version {}",
        sirna_core::FORMAT_VERSION
    );
    if !spec.contains(&heading) {
        bail!(
            "spec/ENVELOPE.md does not declare version {}; its heading and the code disagree",
            sirna_core::FORMAT_VERSION
        );
    }

    println!("spec-lint: {checked} vectors, format version {declared}, spec and code agree");
    Ok(())
}

fn doctor() -> Result<()> {
    let mut problems = Vec::new();
    let root = repo_root();

    // mise exports RUSTUP_TOOLCHAIN, and that variable silently overrides
    // rust-toolchain.toml. When the two disagree the symptom is a bizarre wasm
    // link error much later, so it is worth two lines to catch it here.
    let pinned = std::fs::read_to_string(root.join("rust-toolchain.toml"))
        .ok()
        .and_then(|s| {
            s.lines()
                .find(|l| l.trim_start().starts_with("channel"))
                .and_then(|l| l.split('"').nth(1).map(str::to_owned))
        });

    if let (Some(env), Some(file)) = (std::env::var("RUSTUP_TOOLCHAIN").ok(), pinned.as_deref()) {
        // rustup may hand back a fully-qualified name — `1.95.0` becomes
        // `1.95.0-x86_64-unknown-linux-gnu` — which is the same toolchain, so
        // compare on the channel prefix rather than for exact equality.
        let same = env == file || env.strip_prefix(file).is_some_and(|r| r.starts_with('-'));
        if !same {
            problems.push(format!(
                "RUSTUP_TOOLCHAIN={env} overrides rust-toolchain.toml ({file}). \
                 Fix mise.toml or unset the variable."
            ));
        }
    }

    match std::env::var("CARGO_TARGET_DIR") {
        Ok(dir) if dir.starts_with("/home") => {}
        Ok(dir) => problems.push(format!(
            "CARGO_TARGET_DIR={dir} is not under /home. The root filesystem has very \
             little free space and a multi-target build will fill it."
        )),
        Err(_) => problems.push(
            "CARGO_TARGET_DIR is unset. Run inside mise, or build artifacts land on the \
             root filesystem, which is nearly full."
                .into(),
        ),
    }

    let wasm = std::process::Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).contains("wasm32-unknown-unknown"))
        .unwrap_or(false);
    if !wasm {
        problems.push(
            "wasm32-unknown-unknown is not installed for the active toolchain. \
             Run: rustup target add wasm32-unknown-unknown"
                .into(),
        );
    }

    if problems.is_empty() {
        println!("doctor: environment looks good");
        return Ok(());
    }

    for p in &problems {
        eprintln!("  - {p}");
    }
    bail!("{} problem(s) found", problems.len())
}
